// <auto-generated />
namespace UI_Scheduler_Tool.DataMigrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class AddCurriculum : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(AddCurriculum));
        
        string IMigrationMetadata.Id
        {
            get { return "201504122229437_AddCurriculum"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
